markdown: redcarpet
highlighter: null
permalink: /:title

url: "http://diego.ink"
baseurl: "http://diego.ink"

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
