# Site settings
title: Upcoming ATL Ruby Developer
email: your-email@domain.com
description: "Surprisingly, I am an upcoming Ruby Developer in the Atlanta area. I am currently an Iron Yard student. This is my blog."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: DemonRath0
github_username:  Bartlebyy

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
